port: 4003
env: "development"
appName: "SergeyemBot"
linksUrl: "https://links.sergeyem.ru"
linksPerPage: 10
wordsUrl: "https://easywordsapp.ru"
wordsPerPage: 5
wordsLanguage: "DE"
listsUrl: "https://easylist.sergeyem.ru"
listsPerPage: 100
webhookUrl: "https://185.135.137.48:443/"
db:
  host: ""
  login: "newroot"
  password: "1qaz2wsx"
  dbname: "chatbot"
  maxOpenConns: 25
  maxIdleConns: 25
  maxIdleTime: "15m"
