port: 4043
env: "development"
appName: "SergeyemBot"
linksUrl: "https://links.sergeyem.ru"
linksPerPage: 10
wordsUrl: "https://easywordsapp.ru"
wordsPerPage: 5
wordsLanguage: "DE"
db:
  host: ""
  login: "newroot"
  password: "1qaz2wsx"
  dbname: "chatbot"
  maxOpenConns: 25
  maxIdleConns: 25
  maxIdleTime: "15m"
